<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.arextest</groupId>
  <artifactId>arex-extension</artifactId>
  <version>0.0.3</version>

  <properties>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>Arex-extension is a Java library that defines the extended interface of
    arex.
  </description>
  <url>https://github.com/arextest/arex-extension</url>

  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <dependencies>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <version>1.18.2</version>
    </dependency>
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>dubbo</artifactId>
      <version>2.6.12</version>
    </dependency>
    <dependency>
      <groupId>com.arextest</groupId>
      <artifactId>arex-model</artifactId>
      <version>1.2.2</version>
    </dependency>
  </dependencies>

  <developers>
    <developer>
      <name>AREX</name>
      <email>arex.test.com@gmail.com</email>
      <organization>AREX group</organization>
      <organizationUrl>https://www.arextest.com</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git://github.com/arextest/arex-extension.git</connection>
    <developerConnection>scm:git:ssh://github.com:arextest/arex-extension.git</developerConnection>
    <url>https://github.com/arextest/arex-extension</url>
  </scm>


  <distributionManagement>
    <repository>
      <id>releases</id>
      <url>${releases.repo}</url>
    </repository>
    <snapshotRepository>
      <id>snapshots</id>
      <url>${snapshots.repo}</url>
    </snapshotRepository>
  </distributionManagement>


  <profiles>
    <profile>
      <id>jar</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <releases.repo>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
        </releases.repo>
        <snapshots.repo>https://s01.oss.sonatype.org/content/repositories/snapshots/
        </snapshots.repo>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.6.1</version>
            <executions>
              <execution>
                <phase>package</phase>
                <goals>
                  <goal>shade</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.6.0</version>
            <configuration>
              <source>1.8</source>
              <target>1.8</target>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>3.2.1</version>
            <executions>
              <execution>
                <id>generate-source-jar</id>
                <phase>package</phase>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>3.4.0</version>
            <configuration>
              <doclint>none</doclint>
              <source>8</source>
              <detectJavaApiLink>false</detectJavaApiLink>
            </configuration>
            <executions>
              <execution>
                <id>generate-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.0.1</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.13</version>
            <extensions>true</extensions>
            <configuration>
              <serverId>ossrh</serverId>
              <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
              <autoReleaseAfterClose>true</autoReleaseAfterClose>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>jar-local</id>
      <properties>
        <releases.repo></releases.repo>
        <snapshots.repo></snapshots.repo>
      </properties>
    </profile>
  </profiles>

</project>
